package main

import (
	"fmt"
	. "github.com/zhangyvzhen/go_practice/internal/concurrency"
)

func main() {
	urls := []string{
		"https://www.baidu.com",
		"https://www.qq.com",
		"https://www.taobao.com",
		"https://www.tmall.com",
		"https://www.jd.com",
		"https://www.sina.com.cn",
		"https://www.sohu.com",
		"https://www.163.com",
		"https://www.126.com",
		"https://www.youku.com",
		"https://www.iqiyi.com",
		"https://www.douban.com",
		"https://www.zhihu.com",
		"https://www.weibo.com",
		"https://www.panda.tv",
		"https://www.xiami.com",
		"https://www.meituan.com",
		"https://www.dianping.com",
		"https://www.suning.com",
		"https://www.gome.com.cn",
		"https://www.58.com",
		"https://www.anjuke.com",
		"https://www.lianjia.com",
		"https://www.tujia.com",
		"https://www.qyer.com",
		"https://www.trip.com",
		"https://www.ctrip.com",
		"https://www.sanyue.com",
		"https://www.zhaopin.com",
		"https://www.51job.com",
		"https://www.job5156.com",
		"https://www.lagou.com",
		"https://www.hao123.com",
		"https://www.hao123.com",
		"https://www.chinabank.com.cn",
		"https://www.icbc.com.cn",
		"https://www.ccb.com",
		"https://www.abchina.com",
		"https://www.boc.cn",
		"https://www.cmbchina.com",
		"https://www.nongyibk.com",
		"https://www.hyxbbank.com",
		"https://www.jshb.com",
		"https://www.bocheng.com",
		"https://www.bmw.com.cn",
		"https://www.audi.com.cn",
		"https://www.mercedes-benz.com.cn",
		"https://www.ford.com.cn",
		"https://www.toyota.com.cn",
		"https://www.honda.com.cn",
		"https://www.nissan.com.cn",
		"https://www.sgmw.com.cn",
		"https://www.geely.com",
		"https://www.changan.com.cn",
		"https://www.jac.com.cn",
		"https://www.chery.com.cn",
		"https://www.byd.com",
		"https://www.suzuki.com.cn",
		"https://www.volkswagen.com.cn",
		"https://www.faw.com",
		"https://www.gacmotor.com",
		"https://www.mg.com.cn",
		"https://www.haval.com",
		"https://www.borui.com",
		"https://www.dongfeng.com",
		"https://www.zotye.com",
		"https://www.greatwall.com",
		"https://www.byg.com.cn",
		"https://www.renren.com",
		"https://www.fang.com",
		"https://www.zillow.com",
		"https://www.sohu.com",
		"https://www.wangyi.com",
		"https://www.51zxw.net",
		"https://www.shiye.com",
		"https://www.39.net",
		"https://www.dxy.cn",
		"https://www.91.com",
		"https://www.kuwo.cn",
		"https://www.kugou.com",
		"https://www.ouou.com",
		"https://www.sousou.com",
		"https://www.kankan.com",
		"https://www.acfun.cn",
		"https://www.bilibili.com",
		"https://www.55you.com",
		"https://www.douyin.com",
		"https://www.toutiao.com",
		"https://www.jiemian.com",
		"https://www.163.com",
		"https://www.sina.com.cn",
		"https://www.sohu.com",
		"https://www.douban.com",
		"https://www.lagou.com",
	}

	status := CheckWebsites(OnlineWebsiteChecker, urls)
	trueFlags := 0
	for k, v := range status {
		trueFlags++
		fmt.Println(k, v)
	}
	fmt.Println("success", trueFlags)
	fmt.Println("fail", 100-trueFlags)
}
